### ISSUE TITLE
enabstract里加的模板那句话怎么删除？

### ISSUE THREAD

**Issue by ViyaWEI** [hellckt/SHMTUThesis#11]

**Comment by hellckt** [comment]
那句话? 伪段落的话, 删除`\lipsum[3-6]`就行. 其他内置的都是在 `tex/information.tex` 中进行修改

**Comment by ViyaWEI** [comment]
我通过删除`\lipsum[3-6]`删掉了伪段落，但是ABSTRACT前还有一句"A SAMPLE DOCUMENT FOR LATEX-BASED SHMTU THESIS TEMPLATE"。不知道如何才能删掉

**Comment by hellckt** [comment]
这个需求有点奇怪呢, 正常情况都是要英文标题的. 不需要的话, 可以通过移除 *shmtuthesis-graduate.ltx* 文件中第 117 行到 123 行的内容实现:
```latex
    \chapter*{%
        \bfseries
        \MakeUppercase\shmtu@value@entitle \vskip 2ex
        \begingroup
            \MakeUppercase\shmtu@label@abstractEng
        \endgroup
    }
```
