### ISSUE TITLE
你好，请问参考文献怎么让英文作者的首字母大写，而不是所有字母都大写啊？

### ISSUE THREAD

**Issue by SummerHello12138** [hellckt/SHMTUThesis#12]

**Comment by hellckt** [comment]
https://github.com/hellckt/SHMTUThesis/blob/2aba6751a214ce60bfddf6f80303d6ad8621dbbd/shmtuthesis.cls#L116
将上面这行代码添加 gbstyle=false 参数就可以用默认的英语格式了, 如下所示:
```latex
 \RequirePackage[backend=biber, style=\shmtu@bibstyle, gbstyle=false]{biblatex} 
```

需要其他样式的话可以参考 [biblatex-gb7714-2015](https://mirrors.dgut.edu.cn/CTAN/macros/latex/contrib/biblatex-contrib/biblatex-gb7714-2015/biblatex-gb7714-2015.pdf) 中的说明.
