### ISSUE TITLE
你好，请问在哪设置可以使页眉显示当前页的章标题？是在cls文件里面改吗？

### ISSUE THREAD

**Issue by SummerHello12138** [hellckt/SHMTUThesis#3]

**Comment by hellckt** [comment]
关于界面修改都是在.ltx文件中进行修改，.cls文件主要是用来定义基础框架。
想要在页眉先是当前页章节标题的话，需要在shmtuthesis-graduate.ltx中第66行中插入`\fancyhead[C]{~\zihao{-5}\leftmark}`，如下所示：
```
\fancypagestyle{shmtu@plain}{%
  \fancyhf{}
  \fancyhead[L]{~\zihao{-5}\shmtu@label@subject}
  \fancyhead[C]{~\zihao{-5}\leftmark}
  \fancyhead[R]{\zihao{-5}\shmtu@value@title~}
  \fancyfoot[C]{\small ~{\thepage}~}
}
```
此外，还需要在每个章节名添加`\markboth{章节名}{章节名}`。
注意：仅自己添加的章节需要这样做，摘要、目录、参考文件之类的会自动添加。

此外，需要对页眉和页脚进行更多的定制化设置可以看看[fancyhdr](http://ftp.math.purdue.edu/mirrors/ctan.org/macros/latex/contrib/fancyhdr/fancyhdr.pdf)的文档。

**Comment by SummerHello12138** [comment]
> 关于界面修改都是在.ltx文件中进行修改，.cls文件主要是用来定义基础框架。
> 想要在页眉先是当前页章节标题的话，需要在shmtuthesis-graduate.ltx中第66行中插入`\fancyhead[C]{~\zihao{-5}\leftmark}`，如下所示：
> 
> ```
> \fancypagestyle{shmtu@plain}{%
>   \fancyhf{}
>   \fancyhead[L]{~\zihao{-5}\shmtu@label@subject}
>   \fancyhead[C]{~\zihao{-5}\leftmark}
>   \fancyhead[R]{\zihao{-5}\shmtu@value@title~}
>   \fancyfoot[C]{\small ~{\thepage}~}
> }
> ```
> 
> 此外，还需要在每个章节名添加`\markboth{章节名}{章节名}`。
> 注意：仅自己添加的章节需要这样做，摘要、目录、参考文件之类的会自动添加。
> 
> 此外，需要对页眉和页脚进行更多的定制化设置可以看看[fancyhdr](http://ftp.math.purdue.edu/mirrors/ctan.org/macros/latex/contrib/fancyhdr/fancyhdr.pdf)的文档。

谢谢
