### ISSUE TITLE
安装Texlive 2020新环境，存在CJKfilltwosides环境问题

### ISSUE THREAD

**Issue by Codave** [hellckt/SHMTUThesis#4]
问题描述:

编译文件显示wrong：Environment CJKfilltwosides undefined，错误定位在main文件\maketitle处

解决方法:
在项目sty文件中添加以下两行即可
% xeCJK > 3.8.3 宏包结构改动
\RequirePackage{xeCJKfntef}

**Comment by hellckt** [comment]
#### [原因]

这是由于 ctex 宏集 2.5 版之后不再自动载入 xeCJKfntef 宏包所导致的问题.

#### [解决办法]
 
手动载入在.sty中进行了导入.

#### [改动]

2aba6751a214ce60bfddf6f80303d6ad8621dbbd
