### ISSUE TITLE
你好，请问如何在overleaf中使用呢？

### ISSUE THREAD

**Issue by RZFan525** [hellckt/SHMTUThesis#5]
如题
期待作者解答

**Comment by hellckt** [comment]
把编译器修改为 xeLaTeX 就行, 但是想用 overleaf 在线编译整篇论文的话, 推荐升级为 pro 账号, 否则编译肯定会超时的. 

![image](https://user-images.githubusercontent.com/4927677/114210384-4f524a00-9992-11eb-95b6-87d446dae788.png)

个人推荐下个 latex 的编译器自行编译.

**Comment by RZFan525** [comment]
> 把编译器修改为 xeLaTeX 就行, 但是想用 overleaf 在线编译整篇论文的话, 推荐升级为 pro 账号, 否则编译肯定会超时的.
> 
> ![image](https://user-images.githubusercontent.com/4927677/114210384-4f524a00-9992-11eb-95b6-87d446dae788.png)
> 
> 个人推荐下个 latex 的编译器自行编译.

明白了，我就说为什么超时了，谢谢你
