### ISSUE TITLE
想问下，如何将文献引用改为[1]序号引用，目前编译出来的是thesis第一行

### ISSUE THREAD

**Issue by malin9402** [hellckt/SHMTUThesis#7]

**Comment by hellckt** [comment]
![image](https://user-images.githubusercontent.com/4927677/132229086-cd8ec0cb-fcc2-4a2a-9546-0ac348c8e2b3.png)

上图中的引用方式可以满足你的需求么? 如果都不满足的话, 可以到这里看看他们的文档: https://github.com/hushidong/biblatex-gb7714-2015,这里有更多更详细的说明.
